# Answer 2: R-Type



## R-Type

<!-- TODO: More systematic r-type examples -->

> Annotated on tier `norm[r-type]` in ExMARALDA

We use the ReFlex annotation scheme to give each new referent a referential label.
The original ReFlex paper can be found at https://elib.uni-stuttgart.de/handle/11682/9028.

We use the following 10 labels:

| | R-Type | Abbreviation
|:-|-|-|
| 1 | New | `n` |
| 2 | Unused-Unknown | `u` |
| 3 | Bridging | `b` |
| 4 | Bridging-Contained | `bc` |
| 5 | Bridging-Displaced | `bd` |
| 6 | Given | `g` |
| 7 | Given-Displaced | `gd` |
| (8) | Further-Explanation | `+fe` |
| (9) | Predicative | `+pr` |
| (10) | Generic | `gen` |
| (11) | Introduction | `+intro`


## New

A regular new referent, normally introduced with an indefinite article, referential "this", or a numeral.

> I saw [this man] `n` walking down the street and [a woman] `new` with a stroller.
> There were also [two cars] `n` coming.

> A woman `n` with a black dog `n` was loading groceries `n` into a minivan `n`.

<!-- TODO: Definitions link -->
Questions:

* [New vs. Unused-Unknown](#new-vs.-unused-unknown)
* [Explanation Test](#referent-explanation-test)

## Unused-Unknown

> “Assigned to referring expressions which come with a sufficient amount of descriptive material to enable the hearer to create a new discourse referent without any previous knowledge” (p. 4).

A new referent followed by an indentifying explanation.

The explanation must be a part of the noun phrase containing the referent.
This explanation must also connect the referent to an existing referent in the narrative. 
So, one must be true:

* The explanation contains a given/bridging/unused-unknown referent.
* If no such referent can be found,
the explanation must contain a locative phrase 
that connects the referent to another existing referent.

[More information on identifying explanations](#referent-explanation-test).

> Across the street, a dog was barking.
> The woman `u` [with the dog] `explanation` yelled at it.

> I saw a man and a woman.
> The ball `u` [that [the man] `g` was dribbling] `explanation` fell on the ground.

> I saw a man and a woman walking down the street.
> The dog `u` [that was nearby] `explanation` started barking.

Untagged referents can appear in explanations.

> I was standing in the parking lot.
> The two cars `unused-unkown` [that were coming towards me `untagged` `g` very quickly] `explanation` stopped abruptly.

Referents preceded by possessive pronouns are also unused-unknown,
as long as the possessor is given or bridging.

> I saw a man `n` with his wife `u` and their baby `u`.

Referents preceded by apostrophe-s possession are *also* unused-unknown -
as long as the possessor is given or bridging.

> I saw a man walking down the street.
> The man['s wife] `u` was pushing a baby carriage.

> There was a car on the other side of the parking lot.
> A woman['s dog] `n` was barking loudly.

Note:
If a given referent is referred to in a way that appears
unused-unknown, it should still be tagged `g` 
because once the referent is given, it cannot go back to unused-unknown.

> A man was walking down the street and bouncing a ball.
> ...
> The man `g`, not `u` with the ball stopped bouncing it.


Questions:

* [New vs. Unused-Unknown](#new-vs.-unused-unknown)
* [Referent Explanations](#referent-explanations)
* [Explanation Test](#referent-explanation-test)

## Bridging

> “If an entity does not have a coreferential antecedent but can be understood as unique with respect to a previously introduced situation or scenario, we will be using the label r-bridging” (p. 4).

> “This label is used for non-coreferential anaphoric expressions which are dependent on and unique with respect to a previously introduced scenario” (p. 8).

We use this tag for referents that have not been explicitly introduced but are implied as an essential part of an already known referent (the anchor).

When the anchor of a bridging referent has been introduced,
the listener expects that referent to appear,
and would not be surprised if it was introduced without explanation.

> There were two cars `n` `anchor` coming, and they crashed into each other.
> The drivers `b` got out and called the police.

> There was a family `n` `anchor` walking down the street.
> The father `b` was dribbling a ball.

"Drivers" are bridging from "cars" because we know that cars normally have drivers.
So, when you see "the drivers", you immediately understand that they are the drivers of the two cars.

Similarly, "father" is bridging from "family" because we know that if there is a family, there must be a father.
So, when "father" is introduced, you already implicitly know it's a member of that family.

The anchor and the referent should have a 
[bridging relationship](#bridging relationship) between them.
However, the anchor does not need to be a tagged referent.
Any bridging relationship is enough.

> I saw [a car crash] `untagged` `anchor`!
> The first car `b` stopped short, and the second `b` drove into it.

Note 1:
The bridging referent can sometimes be directly introduced with a pronoun.
This is very common with `drivers`.
In this case, the pronoun should still be treated as bridging.

> The first car `car1` `g` stopped suddenly.
> The car behind didn’t brake in time and hit him `driver1` `b`.

Note 2: 
Bridging relationships do not *always* mean that
referents should be tagged `b`.
If referents are introduced 
in a way that does not reflect the relationship,
they should be tagged as `g` instead.

> A man `man` and a woman `woman1` were walking down the street.
> The two people `couple` `g` 
> were pushing a baby carriage and bouncing a ball.

This happens commonly when referring to `couple` as "two people",
or to `family` as "the three people".

Note 3:
If an anchor is introduced 
in a way that does not show a bridging relationship ("two people"),
but then a referent is introduced 
that only makes sense with a bridging relationship ("the husband"),
that referent should be marked as new.
Consider the following example:

> Two people `couple` `n` were walking down the street.
> The husband `man` `n` was bouncing a ball.

There's no reason that "two people" must include a husband,
so it's not expected in the way that a bridging referent must be.

> Two people `couple` `n` were walking down the street.
> The man `man` `n` was bouncing a ball.

Similar to "husband",
there's no expectation that a group of two people includes a man.

Note 4:
If a given referent is referred to in a way that appears
bridging, it should still be tagged `g` 
because once the referent is given, it cannot go back to bridging.

> Two cars were driving down the street.
> The drivers were clearly speeding `b`.
> The driver `g`, not `b` of the first car stopped suddenly.

Questions

* [What is a bridging relationship](#bridging-relationships)
* [Bridging vs. Bridging-Contained](#bridging-vs.-bridging-contained)

### Bridging-Contained

> "This label applies to a non-coreferential anaphoric expression that is anchored to an embedded phrase” (p. 8).

<!-- TODO: Link to Anchor -->
<!-- TODO: Link bridging relationship -->

Bridging-Contained is similar to Bridging, except that it requires the bridging referent to be in the same noun phrase as its anchor.

Examples:

> The driver `bc` of [the blue car] `anchor` ...

> The driver `bc` of [the closer car] `anchor` ...

> The father `bc` of [the family] `anchor` ...

Since a car is expected to have a driver, and a family to have a father, 
the driver and the father are bridging-contained.

It is possible for the anchor of a bridging-contaied relationship to be the referent in a different bridging relationship
with a different anchor:

> I saw [a car crash] `untagged` `n` `anchor: car1`!
> The man `driver1` `bc` who was in [the car] `car1` `anchor:driver1` `b` got out. 

In this example, "a car crash" acts as an anchor for "the car",
which in turn acts as an anchor for "the man".

Two types of anchors are possible.
The first type is the new anchor. This occurs rarely - mostly with driver - car, trunk - car, father - family

> The driver `bc` of this red car `n` stopped suddenly.

Another type of anchor is a non-new anchor.
Non-new anchors can be `g`, `u`, or `b`.
If the non-new anchor is `u` or `b`, 
it must be connected to a referent that appears before the `bc` referent in question.

> There were two cars. The driver `bc` of the red car `g` stopped suddenly.

The bridging referent and the anchor can be linked by either the prepisition "of",
or another preposition ("in", "on", etc.).
If the preposition is "of", the anchor can be new or non-new.

Examples

> There was a family. The backpack `bc` of the father `b` was blue.

> I saw the driver `bc` of this red car `n` stop suddenly.

> There was a woman across the street. The trunk `bc` of the woman's car `u` was open.

If the preposition is not "of",
only anchors which are non-new can be used for bridging-contained.

> There was a woman. A dog `n` on a leash `n` was barking.

> There was a woman. The dog `n` on a leash `n` was barking.

> There was a lady with her dog `u` on a leash `b`.

'leash' is `b`, because `dog` is the anchor.
However, this anchor does not appear before 'her dog',
and so it does not qualify as a non-new anchor for `bc`.

> A driver `n` in a car `n` slammed on the breaks.

> The driver `n` in a car `n` stopped suddenly.

> There were two cars. I saw the driver `bc` in the red car `g` stop suddenly.

> A woman was unloading groceries.
> The dog `bc` on the leash `u` the woman was holding started barking.

Questions:

* [Bridging vs. Bridging-Contained](#bridging-vs.-bridging-contained)

### Bridging-Displaced

A Bridging-Displaced referent is a Bridging referent with 5 non-empty CU's between the CU containing the referent and the most recent CU containing its anchor.

> There was a couple `couple` `n` ... 
> [5 CU's] ... 
> The mother `woman1` `bd` was just standing there and didn't do anything

> A family `family` `n` was walking down the street.
> On the other side of the road, there was a woman.
> She was taking groceries out of her car.
> She was holding a dog on a leash.
> The dog saw a ball that rolled into the street.
> It barked and chased after the ball.
> The father `man` `bd` yelled and tried to stop the dog.

Questions:

* [How do we count CU's?](#counting-cus)
* [Which CU's are empty CU's?](#empty-cus)

## Given

A given referent is one that has been previously introduced.
It could be introduced either as itself (`man`),
or as part of a conjoined referent without a [bridging relationship](#bridging-relationships) 
(`two people` `n` - `first person` `g`, `two cars` `n` - `the first car` `g`), 
or through the enumeration of its elements (`a man` `n` and `a woman` `n` - `the two people` `g`).

> There was a man `man`.
> He `man` `g` was dribbling a ball.

> There were these two people `couple` walking.
> One of them `man` `g` had a ball.

> There were two cars `cars` approaching the scene.
> The first car `car1` `g` stopped, and the second car `car2` `g` bumped into it.

> The drivers `drivers` of the two cars stopped suddenly.
> The first one `driver1` `g` got out and called the police,
> and the second one `driver2` `g` started yelling.

> There was a man `man` who was dribbling a ball and a woman `woman1` with a stroller.
> The two people `couple` `g` were crossing the street.

> There were two people `couple` crossing the street.
> The first person `man` `g` was bouncing a ball,
> and the second `woman1` `g` was pushing a stroller.

Questions:

* [When a conjoined referent appears, are members of it treated as given or bridging?](#conjoined-referent-members)


### Given-Displaced

A Given-Displaced referent is a Given referent with 5 non-empty CU's between the CU containing the referent and the most recent CU containing the same referent.

> There was a man ...
> [ 5 CU’s ] ... 
> The man `gd` was running to catch the ball.

> A man and a woman were walking.
> There were two cars coming ...
> [ 5 CU’s ] ... 
> The man `gd` helped the lady with her groceries.

> A man `man` and a woman were walking together.
> The woman was pushing a stroller.
> Across the street, there was a different woman.
> She was putting groceries into her car.
> But she was also holding a dog on a leash.
> The dog tried to pull away from her, to chase a ball.
> The man `man` `gd` looked on in horror as the dog ran into the street.

Questions:

* [How do we count CU's?](#counting-cus)
* [Which CU's are empty CU's?](#empty-cus)

## Further-Explanation

Further Explanation was brought in to solve issues like the following:

> [Two cars] `cars` `n`, [a blue one] `car1` `???` and [a white one] `car2` `???`, were driving down the street.

In this example, it's difficult to determine the r-type of `car1` and `car2`.
They're introduced like new referents, leading us towards `n`, but then it would seem that `car1` was introduced twice -
once in `cars`, and once in `car1`.

To resolve this, we use the `+fe` tag.
`+fe` attaches to the end of the existing annotation, and we get:

* `cars` `n`
* `car1` `n+fe`
* `car2` `n+fe`

When a referent is annotated as `+fe`, it repeats the most recent r-type, plus `+fe`.

> A dog ran into the street. A car `car1` `n` (a blue one `car1` `n+fe`) stopped suddenly.

> Two cars `cars` `n`,
> [a blue] `car1` `n+fe` and [a white one] `car2` `n+fe`,
> stopped suddenly.

> Two cars `cars` `n` were driving down the road,
> with just one driver in each.
> The cars `cars` `g`,
> [a blue] `car1` `g+fe` and [a white one] `car2` `g+fe`,
> stopped suddenly.

## Predicative

Similar to Further Explanation, Predicative solves the issue with:

> There was a car `car1` `n`. It looked like a blue one `car1` `???`.

In this example, it is unclear what r-type "a blue one" should receive.
We answer this question with the predicative tag.

Predicative referents do not introduce new things or people.
Instead,
they attribute a new characteristic to an already-existing referent.

These already-existing referents are introduced
before the verbs "to be", "to look like", "to seem like", etc.
Usually,
the already-existing referent is the subject of one of these verbs.

> There was a car.
> It `referent` was [a blue car] `characteristic`.

Predicative referents are one of:

* Generic
* Non-Generic

Generic predicatives assign a characteristic to a referent,
as described above.
Almost all predicatives are generic.

Generic predicative referents are tagged as `gen+pr`.

> There was a car `car1` `n`.
> It `car2` `g` `subject` was a blue car `car1` `gen+pr` `characteristic`.

As we see here, no new thing/person was introduced by the phrase "a blue car", it just added a new characteristic to `car1`.

> There were two cars `cars` `n`.
> The first car `car1` `g` `subject` was a blue car `car1` `gen+pr` `characteristic`.

Similarly, "a blue car" does not introduce a new referent, but just adds a characteristic to an existing one.

Non-Generic predicatives link two existing referents.
These predicatives are annotated with `+pr` (`n+pr`, `b+pr`, `u+pr`, `g+pr`).

> There was a cocker spaniel walking down the street.
> It reminded me of my dog who was at home.
> Suddenly I realized:
> The cocker spaniel `referent1` was my dog `g+pr` `referent2`!

> Two cars crashed.
> A bald guy called the police.
> In fact, the bald guy `referent1` 
> was the driver `referent2` `bc+pr` of the first car.

> A dog ran in front of a car, and
> that car and another crashed together.
> A bald guy called the police.
> In fact bald guy was the one `u+pr` who stopped for the dog.

There are two ways to identify non-generic predicatives:

* Reversal: A non-generic predicative remains grammatical 
with the two referents reversed

> In fact, the driver of the first car was the bald guy.

This does not work with `gen+pr` referents.

> \* There was a car.
> A blue car was it.

* Defnite Article: If an article is used 
with the predicative referent (`referent2`),
it must be definite.
An indefinite article implies a generic predicative.

> \* In fact, the driver of the first car was a bald guy.

With an indefinite article,
the listener has no reason to believe that the driver of the first car 
is the same bald guy refereced earlier.

## Generic

Refers to a gerneric referent,
doesn't name a particular thing/character in the narrative,
but refers to a class of things in general.

> The dog jumped at the ball.
> You know, because it's a dog `gen+pr`,
> and a dog `gen` is always gonna want to jump at a ball.

The majority of generic referents that appeared in the data are [predicatives](#predicative). These are tagged as `gen+pr`.

However,
there are cases where a "referent" is generic, but not predicative.
In the example above, "it's a dog" is generic and predicative,
but "a dog is always ..." is only generic.
These non-predicative generics are tagged as `gen`.

We do not want to tag *all* generics that occur in the narrative.
We only want to tag generics that might be confused for annotated referents.
So, tagged generic referents must:

* Refer to the class of things containing the referent they might be confused with

* Agree in number with the referent they might be confused with

> The dog jumped at a ball.
> You know, dogs `untagged` are always gonna want to jump at a ball.

## Introductions

Introductions appear at the beginning of narratives.
The speaker introduces the main events of the narrative,
before going back and explaining more in-depth.

> Oh my gosh I just saw this car crash!
> A man and a woman were walking...

Introductions can identified by two main factors:

* They summarize a portion of the later narrative
* They are temporally displaced - after the introduction,
the speaker moves to a different time in the story's narrative.

> I saw a car crash involving a little dog. `introduction`
> So, I was in the parking lot, and a man and a woman were walking,
> And a woman was unloading her groceries, she had a little dog.
> And there were two cars which bumped into each other.

The introduction in the example above summarizes the whole story,
after which the speaker moves to the very beginning of the main story,
and not to the events after the crash.

In most cases, it is clear what is or is not an introduction. 
If you hesitate, discuss with other annotators.

Referents that occur in introductions are tagged as their base r-type `+intro`,
and are not counted for any given/bridging/unused-unknown determinations 
outside the introduction.

> I just saw a car crash, where a dog `dog` `n+intro` almost got hit!
> So, a man and a woman were walking, and a car `car1` `n (not b)` stopped suddenly ...

Since `dog` appears in the intro, its r-type is tagged as `n+intro`.

Although there is a `car crash <-> car1` bridging relationship,
the car crash appears in the intro, and so is not counted for later bridging.
