# Answer 3: Conjoined Referents

> Annotated on the `norm [conj_referent]` tier in Exmaralda

Out of our 19 referents, there are 4 conjoined referents:

1. couple
2. family
3. cars
4. drivers

For each conjoined referent, we want to mark whether or not it is explained:

* Unexplained `0`
* Explained `1`

An explanation is an enumeration of conjoined referent elements with indefinite articles/possessive pronouns.
The enumeration has to come right after the conjoined referent. 
The elements in the enumeration are tagged as `n` if the conjoined referent was `n`, and as `g` if the conjoined referent was `g`.
Normally in writing the explanation is separated by a comma or is in brackets.

Such explanations do not appear often, so the majority of conjoined referents will be unexplained.

Generally, members of an explained conjoined referent will be treated as [+fe](#further-explanation)

> There were two cars `cars` `n` `1`, a white one `car1` `n+fe` and a blue one `car2` `n+fe`. 

<!-- ??? Is woman1 b+fe ??? -->
> There was a family `family` `n` `1`, a mom `woman1` `n+fe`, a dad `man` `n+fe` and a baby `baby` `n+fe`.

> There was a family `family` `n` `0` walking down the street. The family `family` `g` `1` (a mom `woman1` `g+fe`, a dad `man` `g+fe` and a baby `baby` `g+fe`) looked happy.
 
> There was a couple `couple` `n` `0` who was crossing the road.
 
Please note that the elements of the explanation can not be subjects of finite main clauses that follow the clause with the conjoined referent. So, the following example is not an explanation:
 
> There was a couple `couple` `n` `0`. The man was playing with a ball. The woman was holding a baby.
