---
title: "Referent Annotation Guidelines"
author: ""
date: "7/14/2020"
output:
  html_document:
    css: style.css
    toc: true
    toc_float:
      collapsed: false
    
---


```{r setup, include=FALSE}
```

# Section 1. Research Questions

1. Do heratige speakers introduce more referents than monolinguals?

2. Do heratige speakers use different types of referents than monolinguals?

3. Do heratige speakers explain conjoined referents more often than monolinguals?


# Section 2. Main Answers

# Answer 1: Counting Referents
## 2.1 Referents

> Annotated on tier `norm[referent]` in ExMARALDA

We have a list of 19 possible referents, and we count how many of these 19 referents each speaker introduces:

1. man (with the ball)
2. woman1 (with the stroller)
3. couple (man and woman1) - *conjoined referent*
4. family (man+woman1+baby) - *conjoined referent*
5. ball
6. stroller
7. baby
8. woman2 (with the dog)
9. dog
10. leash
11. groceries
12. trunk
13. car1 (blue one, comes in first, gets hit)
14. car2 (white one, comes in second, hits car1)
15. car3 (red one, woman with groceries)
16. cars (car1 + car2) - *conjoined referent*
17. driver1 (blue car, calls 911)
18. driver2 (white car)
19. drivers (driver1 + driver2) - *conjoined referent*

Referents should be tagged 
[starting with the beginning determiner, and ending with the last word of the referent noun](#span-of-referent-annotations).

There can be [repetitions](#identifying-repetitions) in the narrative, when the speaker produces the same referent several times in a row. Please refer to the linked section to see how to tag those.

See also:

* [Referent Questions](#referents-1)
* [Phrase Questions (e.g. "each other", "one of the")](#phrases)


# Answer 2: Counting Types of Referents (R-Types)

## 2.2 R-Type

<!-- TODO: More systematic r-type examples -->

> Annotated on tier `norm[r-type]` in ExMARALDA

We use the ReFlex annotation scheme to give each new referent a referential label.
The original ReFlex paper can be found at https://elib.uni-stuttgart.de/handle/11682/9028.

We use the following 11 labels:

| | R-Type | Abbreviation
|:-|-|-|
| 1 | New | `n` |
| 2 | Unused-Unknown | `u` |
| 3 | Bridging | `b` |
| 4 | Bridging-Contained | `bc` |
| 5 | Bridging-Displaced | `bd` |
| 6 | Given | `g` |
| 7 | Given-Displaced | `gd` |
| (8) | Further-Explanation | `+fe` |
| (9) | Predicative | `+pr` |
| (10) | Generic | `gen` |
| (11) | Introduction | `+intro`


## 2.2.1 New

A regular new referent, normally introduced with an indefinite article, referential "this", or a numeral.

> I saw [this man] `n` walking down the street and [a woman] `n` with a stroller.
> There were also [two cars] `n` coming.

> A woman `n` with a black dog `n` was loading groceries `n` into a minivan `n`.

<!-- TODO: Definitions link -->
Questions:

* [New vs. Unused-Unknown](#new-vs-unused-unknown)
* [Explanation Test](#referent-explanation-test)

## 2.2.2 Unused-Unknown

> “Assigned to referring expressions which come with a sufficient amount of descriptive material to enable the hearer to create a new discourse referent without any previous knowledge” (p. 4).

A new referent followed by an indentifying explanation.

The explanation must be a part of the noun phrase containing the referent.
This explanation must also connect the referent to an existing referent in the narrative. 
So, one must be true:

* The explanation contains a given/bridging/unused-unknown referent.
* If no such referent can be found,
the explanation must contain a locative phrase 
that connects the referent to another existing referent.

[More information on identifying explanations](#referent-explanation-test).

> Across the street, a dog was barking.
> The woman `u` [with the dog] `explanation` yelled at it.

> I saw a man and a woman.
> The ball `u` [that [the man] `g` was dribbling] `explanation` fell on the ground.

> I saw a man and a woman walking down the street.
> The dog `u` [that was nearby] `explanation` started barking.

Untagged referents can appear in explanations.

> I was standing in the parking lot.
> The two cars `unused-unkown` [that were coming towards me `untagged` `g` very quickly] `explanation` stopped abruptly.

Referents preceded by possessive pronouns are also unused-unknown,
as long as the possessor is given or bridging.

> I saw a man `n` with his wife `u` and their baby `u`.

Referents preceded by apostrophe-s possession are *also* unused-unknown -
as long as the possessor is given or bridging.

> I saw a man walking down the street.
> The man['s wife] `u` was pushing a baby carriage.

> There was a car on the other side of the parking lot.
> A woman['s dog] `n` was barking loudly.

Note:
If a given referent is referred to in a way that appears
unused-unknown, it should still be tagged `g` 
because once the referent is given, it cannot go back to unused-unknown.

> A man was walking down the street and bouncing a ball.
> ...
> The man `g`, not `u` with the ball stopped bouncing it.


Questions:

* [New vs. Unused-Unknown](#new-vs-unused-unknown)
* [Referent Explanations](#referent-explanations)
* [Explanation Test](#referent-explanation-test)

## 2.2.3 Bridging

> “If an entity does not have a coreferential antecedent but can be understood as unique with respect to a previously introduced situation or scenario, we will be using the label r-bridging” (p. 4).

> “This label is used for non-coreferential anaphoric expressions which are dependent on and unique with respect to a previously introduced scenario” (p. 8).

We use this tag for referents that have not been explicitly introduced but are implied as an essential part of an already known referent (the anchor).

When the anchor of a bridging referent has been introduced,
the listener expects that referent to appear,
and would not be surprised if it was introduced without explanation.

> There were two cars `n` `anchor` coming, and they crashed into each other.
> The drivers `b` got out and called the police.

> There was a family `n` `anchor` walking down the street.
> The father `b` was dribbling a ball.

"Drivers" are bridging from "cars" because we know that cars normally have drivers.
So, when you see "the drivers", you immediately understand that they are the drivers of the two cars.

Similarly, "father" is bridging from "family" because we know that if there is a family, there must be a father.
So, when "father" is introduced, you already implicitly know it's a member of that family.

The anchor and the referent should have a 
[bridging relationship](#bridging-relationships) between them.
However, the anchor does not need to be a tagged referent.
Any bridging relationship is enough.

> I saw [a car crash] `untagged` `anchor`!
> The first car `b` stopped short, and the second `b` drove into it.

Note 1:
The bridging referent can sometimes be directly introduced with a pronoun.
This is very common with `drivers`.
In this case, the pronoun should still be treated as bridging.

> The first car `car1` `g` stopped suddenly.
> The car behind didn’t brake in time and hit him `driver1` `b`.

Note 2: 
Bridging relationships do not *always* mean that
referents should be tagged `b`.
If referents are introduced 
in a way that does not reflect the relationship,
they should be tagged as `g` instead.

> A man `man` and a woman `woman1` were walking down the street.
> The two people `couple` `g` 
> were pushing a baby carriage and bouncing a ball.

This happens commonly when referring to `couple` as "two people",
or to `family` as "the three people".

Note 3:
If an anchor is introduced 
in a way that does not show a bridging relationship ("two people"),
but then a referent is introduced 
that only makes sense with a bridging relationship ("the husband"),
that referent should be marked as new.
Consider the following example:

> Two people `couple` `n` were walking down the street.
> The husband `man` `n` was bouncing a ball.

There's no reason that "two people" must include a husband,
so it's not expected in the way that a bridging referent must be.

> Two people `couple` `n` were walking down the street.
> The man `man` `n` was bouncing a ball.

Similar to "husband",
there's no expectation that a group of two people includes a man.

Note 4:
If a given referent is referred to in a way that appears
bridging, it should still be tagged `g` 
because once the referent is given, it cannot go back to bridging.

> Two cars were driving down the street.
> The drivers were clearly speeding `b`.
> The driver `g`, not `b` of the first car stopped suddenly.

Questions

* [What is a bridging relationship](#bridging-relationships)
* [Bridging vs. Bridging-Contained](#bridging-vs-bridging-contained)

### 2.2.4 Bridging-Contained

> "This label applies to a non-coreferential anaphoric expression that is anchored to an embedded phrase” (p. 8).

<!-- TODO: Link to Anchor -->
<!-- TODO: Link bridging relationship -->

Bridging-Contained is similar to Bridging, except that the anchor must be in the same noun phrase as the bridging referent. In the majority of cases, the anchor must be non-new, i.e. `given`, `unused-unknown`, or `bridging`, except for the cases when the bridging referent and its anchor are linked with the preposition *of* (see below).

Examples:

> The driver `bc` of [the blue car] `anchor` ...

> The driver `bc` of [the closer car] `anchor` ...

> The father `bc` of [the family] `anchor` ...

Since a car is expected to have a driver, and a family to have a father, 
the driver and the father are bridging-contained.

It is possible for the anchor of a bridging-contaied relationship to be the referent in a different bridging relationship
with a different anchor:

> I saw [a car crash] `untagged` `n` `anchor: car1`!
> The man `driver1` `bc` who was in [the car] `car1` `anchor:driver1` `b` got out. 

In this example, "a car crash" acts as an anchor for "the car",
which in turn acts as an anchor for "the man".

Two **types of anchors** are possible.
The first type is **a new anchor**. This occurs rarely - mostly with driver - car, trunk - car, father - family

> The driver `bc` of this red car `n` stopped suddenly.

Another type of anchor is **a non-new anchor**.
Non-new anchors can be `g`, `u`, or `b`.
If the non-new anchor is `u` or `b`, 
it must be connected to a referent that appears before the `bc` referent in question.

> There were two cars. The driver `bc` of the red car `g` stopped suddenly.

The bridging referent and the anchor can be linked by either the prepisition "of",
or another preposition ("in", "on", etc.).
If the preposition is "of", the anchor can be new or non-new.

Examples

> There was a family. The backpack `bc` of the father `b` was blue.

> I saw the driver `bc` of this red car `n` stop suddenly.

> There was a woman across the street. The trunk `bc` of the woman's car `u` was open.

If the preposition is not "of",
only anchors which are non-new can be used for bridging-contained.

> There was a woman. A dog `n` on a leash `b` was barking.

> There was a woman. The dog `n` on a leash `b` was barking.

> There was a lady with her dog `u` on a leash `b`.

In the three examples above, 'leash' is `b`, because `dog` is the anchor.
 However, this anchor does not appear before 'a/the/her dog',
 and so it does not qualify as a non-new anchor for `bc`.

> A driver `n` in a car `n` slammed on the breaks.

> The driver `n` in a car `n` stopped suddenly.

> There were two cars. I saw the driver `bc` in the red car `g` stop suddenly.

> A woman was unloading groceries.
> The dog `bc` on the leash `u` the woman was holding started barking.

Questions:

* [Bridging vs. Bridging-Contained](#bridging-vs-bridging-contained)

### 2.2.5 Bridging-Displaced

A Bridging-Displaced referent is a Bridging referent with 5 non-empty CU's between the CU containing the referent and the most recent CU containing its anchor.

> There was a couple `couple` `n` ... 
> [5 CU's] ... 
> The mother `woman1` `bd` was just standing there and didn't do anything

> A family `family` `n` was walking down the street.
> On the other side of the road, there was a woman.
> She was taking groceries out of her car.
> She was holding a dog on a leash.
> The dog saw a ball that rolled into the street.
> It barked and chased after the ball.
> The father `man` `bd` yelled and tried to stop the dog.

Questions:

* [How do we count CU's?](#counting-cus)
* [Which CU's are empty CU's?](#empty-cus)

## 2.2.6 Given

A given referent is one that has been previously introduced.
It could be introduced either as itself (`man`),
or as part of a conjoined referent without a [bridging relationship](#bridging-relationships) 
(`two people` `n` - `first person` `g`, `two cars` `n` - `the first car` `g`), 
or through the enumeration of its elements (`a man` `n` and `a woman` `n` - `the two people` `g`).

> There was a man `man`.
> He `man` `g` was dribbling a ball.

> There were these two people `couple` walking.
> One of them `man` `g` had a ball.

> There were two cars `cars` approaching the scene.
> The first car `car1` `g` stopped, and the second car `car2` `g` bumped into it.

> The drivers `drivers` of the two cars stopped suddenly.
> The first one `driver1` `g` got out and called the police,
> and the second one `driver2` `g` started yelling.

> There was a man `man` who was dribbling a ball and a woman `woman1` with a stroller.
> The two people `couple` `g` were crossing the street.

> There were two people `couple` crossing the street.
> The first person `man` `g` was bouncing a ball,
> and the second `woman1` `g` was pushing a stroller.

Questions:

* [When a conjoined referent appears, are members of it treated as given or bridging?](#conjoined-referent-members)


## 2.2.7 Given-Displaced

A Given-Displaced referent is a Given referent with 5 non-empty CU's between the CU containing the referent and the most recent CU containing the same referent.

> There was a man ...
> [ 5 CU’s ] ... 
> The man `gd` was running to catch the ball.

> A man and a woman were walking.
> There were two cars coming ...
> [ 5 CU’s ] ... 
> The man `gd` helped the lady with her groceries.

> A man `man` and a woman were walking together.
> The woman was pushing a stroller.
> Across the street, there was a different woman.
> She was putting groceries into her car.
> But she was also holding a dog on a leash.
> The dog tried to pull away from her, to chase a ball.
> The man `man` `gd` looked on in horror as the dog ran into the street.

Questions:

* [How do we count CU's?](#counting-cus)
* [Which CU's are empty CU's?](#empty-cus)

## 2.2.8 Further-Explanation

Further Explanation was brought in to solve issues like the following:

> [Two cars] `cars` `n`, [a blue one] `car1` `???` and [a white one] `car2` `???`, were driving down the street.

In this example, it's difficult to determine the r-type of `car1` and `car2`.
They're introduced like new referents, leading us towards `n`, but then it would seem that `car1` was introduced twice -
once in `cars`, and once in `car1`.

To resolve this, we use the `+fe` tag.
`+fe` attaches to the end of the existing annotation, and we get:

* `cars` `n`
* `car1` `n+fe`
* `car2` `n+fe`

When a referent is annotated as `+fe`, it repeats the most recent r-type, plus `+fe`.

> A dog ran into the street. A car `car1` `n` (a blue one `car1` `n+fe`) stopped suddenly.

> Two cars `cars` `n`,
> [a blue] `car1` `n+fe` and [a white one] `car2` `n+fe`,
> stopped suddenly.

> Two cars `cars` `n` were driving down the road,
> with just one driver in each.
> The cars `cars` `g`,
> [a blue] `car1` `g+fe` and [a white one] `car2` `g+fe`,
> stopped suddenly.

## 2.2.9 Predicative

Similar to Further Explanation, Predicative solves the issue with:

> There was a car `car1` `n`. It looked like a blue one `car1` `???`.

In this example, it is unclear what r-type "a blue one" should receive.
We answer this question with the predicative tag.

Predicative referents do not introduce new things or people.
Instead,
they attribute a new characteristic to an already-existing referent.

These already-existing referents are introduced
before the verbs "to be", "to look like", "to seem like", etc.
Usually,
the already-existing referent is the subject of one of these verbs.

> There was a car.
> It `referent` was [a blue car] `characteristic`.

Predicative referents are one of:

* Generic
* Non-Generic

Generic predicatives assign a characteristic to a referent,
as described above.
Almost all predicatives are generic.

Generic predicative referents are tagged as `gen+pr`.

> There was a car `car1` `n`.
> It `car2` `g` `subject` was a blue car `car1` `gen+pr` `characteristic`.

As we see here, no new thing/person was introduced by the phrase "a blue car", it just added a new characteristic to `car1`.

> There were two cars `cars` `n`.
> The first car `car1` `g` `subject` was a blue car `car1` `gen+pr` `characteristic`.

Similarly, "a blue car" does not introduce a new referent, but just adds a characteristic to an existing one.

Non-Generic predicatives link two existing referents.
These predicatives are annotated with `+pr` (`n+pr`, `b+pr`, `u+pr`, `g+pr`).

> There was a cocker spaniel walking down the street.
> It reminded me of my dog who was at home.
> Suddenly I realized:
> The cocker spaniel `referent1` was my dog `g+pr` `referent2`!

> Two cars crashed.
> A bald guy called the police.
> In fact, the bald guy `referent1` 
> was the driver `referent2` `bc+pr` of the first car.

> A dog ran in front of a car, and
> that car and another crashed together.
> A bald guy called the police.
> In fact bald guy was the one `u+pr` who stopped for the dog.

There are two ways to identify non-generic predicatives:

* Reversal: A non-generic predicative remains grammatical 
with the two referents reversed

> In fact, the driver of the first car was the bald guy.

This does not work with `gen+pr` referents.

> \* There was a car.
> A blue car was it.

* Defnite Article: If an article is used 
with the predicative referent (`referent2`),
it must be definite.
An indefinite article implies a generic predicative.

> \* In fact, the driver of the first car was a bald guy.

With an indefinite article,
the listener has no reason to believe that the driver of the first car 
is the same bald guy refereced earlier.

## 2.2.10 Generic

Refers to a gerneric referent,
doesn't name a particular thing/character in the narrative,
but refers to a class of things in general.

> The dog jumped at the ball.
> You know, because it's a dog `gen+pr`,
> and a dog `gen` is always gonna want to jump at a ball.

The majority of generic referents that appeared in the data are [predicatives](#predicative). These are tagged as `gen+pr`.

However,
there are cases where a "referent" is generic, but not predicative.
In the example above, "it's a dog" is generic and predicative,
but "a dog is always ..." is only generic.
These non-predicative generics are tagged as `gen`.

We do not want to tag *all* generics that occur in the narrative.
We only want to tag generics that might be confused for annotated referents.
So, tagged generic referents must:

* Refer to the class of things containing the referent they might be confused with

* Agree in number with the referent they might be confused with

> The dog jumped at a ball.
> You know, dogs `untagged` are always gonna want to jump at a ball.

## 2.2.11 Introductions

Introductions appear at the beginning of narratives.
The speaker introduces the main events of the narrative,
before going back and explaining more in-depth.

> Oh my gosh I just saw this car crash!
> A man and a woman were walking...

Introductions can identified by two main factors:

* They summarize a portion of the later narrative
* They are temporally displaced - after the introduction,
the speaker moves to a different time in the story's narrative.

> I saw a car crash involving a little dog. `introduction`
> So, I was in the parking lot, and a man and a woman were walking,
> And a woman was unloading her groceries, she had a little dog.
> And there were two cars which bumped into each other.

The introduction in the example above summarizes the whole story,
after which the speaker moves to the very beginning of the main story,
and not to the events after the crash.

In most cases, it is clear what is or is not an introduction. 
If you hesitate, discuss with other annotators.

Referents that occur in introductions are tagged as their base r-type `+intro`,
and are not counted for any given/bridging/unused-unknown determinations 
outside the introduction.

> I just saw a car crash, where a dog `dog` `n+intro` almost got hit!
> So, a man and a woman were walking, and a car `car1` `n (not b)` stopped suddenly ...

Since `dog` appears in the intro, its r-type is tagged as `n+intro`.

Although there is a `car crash <-> car1` bridging relationship,
the car crash appears in the intro, and so is not counted for later bridging.

<!--chapter:end:01-rtype.Rmd-->

# Answer 3: Counting Conjoined Referents

> Annotated on the `norm [conj_referent]` tier in Exmaralda

Out of our 19 referents, there are 4 conjoined referents:

1. couple
2. family
3. cars
4. drivers

For each conjoined referent, we want to mark whether or not it is explained:

* Unexplained `0`
* Explained `1`

An explanation is an enumeration of conjoined referent elements with indefinite articles/possessive pronouns.
The enumeration has to come right after the conjoined referent. 
The elements in the enumeration are tagged as `n` if the conjoined referent was `n`, and as `g` if the conjoined referent was `g`.
Normally in writing the explanation is separated by a comma or is in brackets.

Such explanations do not appear often, so the majority of conjoined referents will be unexplained.

Generally, members of an explained conjoined referent will be treated as [+fe](#further-explanation)

> There were two cars `cars` `n` `1`, a white one `car1` `n+fe` and a blue one `car2` `n+fe`. 

<!-- ??? Is woman1 b+fe ??? -->
> There was a family `family` `n` `1`, a mom `woman1` `n+fe`, a dad `man` `n+fe` and a baby `baby` `n+fe`.

> There was a family `family` `n` `0` walking down the street. The family `family` `g` `1` (a mom `woman1` `g+fe`, a dad `man` `g+fe` and a baby `baby` `g+fe`) looked happy.
 
> There was a couple `couple` `n` `0` who was crossing the road.
 
Please note that the elements of the explanation can not be subjects of finite main clauses that follow the clause with the conjoined referent. So, the following example is not an explanation:
 
> There was a couple `couple` `n` `0`. The man was playing with a ball. The woman was holding a baby.

<!--chapter:end:02-conjoined-referents.Rmd-->

# Section 3. Questions & Answers

## 3.1 Referents

### 3.1.1 Span of Referent Annotations

When tagging referents,
we want to include both the determiner and the referent noun.

However,
we do not want to include prepositional phrases or relative clauses 
that may be attached to the referent noun.
If we did, we would obscure other referents 
contained within those phrases and clauses.

So, when tagging referents:

* Start with the first determiner of the referent noun phrase
* End with the last word of the referent noun

> I saw [a man] `man` and [a woman] `woman1`.

> I saw [a big tall man] `man`.

> I saw [two very fast cars] `cars`.

> I saw [all of the car drivers] `drivers` get out of the car.

> I saw [the older woman] `woman` with [a barking dog] `dog`.

> [A big tall man] `man` 
> who was bouncing [a ball] `ball` walked down the street.

If errors or repeitions occur after the determiner,
but before the final referent noun,
and the determiner is not repeated,
we treat the repition as intervening material,
and tag everything between the two.

> While I was watching,
> [a big - er well not really that big - man] `man` 
> who was bouncing a ball started walking down the street.

> On the other side of the street,
> There was [a boy - uh not boy - man] `man` bouncing a ball.

Note:
If the determiner *was* repeated ("a boy - uh not a boy - a man"),
we would tag only the last instance of the referent.
See: [Repititions](#repititions)

### 3.1.2 Groceries

> What noun phrases should we tag as `groceries`? What noun phrases should we not?

Generally, `groceries` should be a mass noun.
Here's a list of things we've decided to tag as `groceries`, and a list of things we've decided not to.

Groceries:

* groceries
* produce
* shopping
* stuff
* food

Not Groceries:

* (grocery) bags
* baggage
* fruits

### 3.1.3 Grocery Consistency

> What if someone introduces `groceries` as "fruits" `untagged`,
> but then later refers to "her groceries" `tagged`?
> Should we tag "fruits"?

Yes. The same is true of the reverse.
If "her groceries" appears, and "fruits" follows, we should tag both.

### 3.1.4 Family vs. Couple

> Does the pronoun "they" refer to `family` or `couple`?

Generally:

* If all the members of the family have been introduced,
"they" refers to the family.

> There was a man, a woman, and a baby.
> They `family` crossed the street.

* If only man and woman1 (and maybe stroller) have been introduced,
"they" refers to the couple, instead.

> There was a man and a woman.
> They `couple` crossed the street.

> There was a man and a woman and a stroller.
> They `couple` went across the street.

However: If there’s a man and a woman *with* a baby,
we treat it as a couple,
as the baby is just additional information
attached to the man or the woman.

> There was a man and a woman with a baby.
> They `couple` crossed the street. 

## 3.2 R-Types

### 3.2.1 R-Type Hierarchy

> Multiple r-types apply to this referent. Which shall I choose?

If multiple r-types apply,
choose the highest ranking r-type in the r-type hierarchy:

`g(d) > bc > b(d) > u > n`

> The driver `driver2` `u` who was behind the guy `driver1` `bc` 
> in the blue car `car1` `g` was forced to stop suddenly.
  
Both `bc` and `u` apply to `driver1`, but `bc` ranks higher.

### 3.2.2 New vs Unused Unknown

> Should I tag this referent as New or Unused-Unknown?

Tag as `u` if:

* The explanation that comes after [contains a given referent](#explanation-given-referent)

* The explanation that comes after [contains a bridging or unused-unknown referent](#explanation-bridging-or-unused-unknown-referent)

* The referent is possessed by a given/bridging/unused referent represented by [possessive pronoun](#possessive-pronouns)

> There was a woman, and [her dog] `u` ran.

* The referent is possessed by a given/bridging referent represented by [apostrophe s](#apostrophe-s)

> There were a man with his family. The man `g` ['s ball] `u` rolled away.
> There was a family. The father `b` ['s ball] `u` rolled away.

The possessing referent could theortically be unused-unknown too but we haven't seen such cases.

* The explanation contains a [locative phrase]
connecting the referent to another existing referent.

> I saw a man and a woman walking down the street.
> The dog `u` [that was nearby] `explanation` started barking.

Otherwise, tag as `n`.

> I was standing in a parking lot. A woman `n` ['s dog] `n` suddenly ran in front of two cars.

[More information on identifying explanations](#referent-explanation-test).

### 3.2.3 Explanation containing Given Referent

> Does this explanation contain a given referent?

An explanation contains a given referent if:

* It contains a tagged referent marked `g`
* It contains an untagged referent that has been previously introduced

<!--
* `g` referent => Y
* `n` referent => N
* `u` referent => N
* given un-annotated => Y
* non-given un-annotated => N

Phrase types:
* relative clause
* prepositional phrase
-->

> The man who was holding the ball `g` and talking to a woman dropped it.

Explanation: "who was holding the ball and talking to a woman"

"the ball": `g`

"a woman": `n`

Explanation contains a given referent.
Tag "the man" as `u`.

> The man who was holding a ball `n` dropped it.

Explanation: "who was holding a ball"

"a ball": `n`

Explanation does not contain a given referent.
Tag "the man" as `n`.

<!-- TODO: "The man who was holding the woman's ball -->
> The man with the woman `g` 's ball `u` dropped it.

Explanation: "with the woman's ball"

"the woman": `g`

"'s ball": `u`

Explanation contains a given referent.
Tag "the man" as `u`.

> A couple was walking down the road.
> A woman across the street was unloading groceries from her car.

Explanation: "across the street"

"the street": `g`

Explanation contains a given referent.
Tag "a woman" as `u`

Note: Although "the street" is not annotated, it has been introduced in the narrative.
So, it is considered a given referent.

> A couple was walking with a stroller.
> A woman with a dog was unloading groceries from her car.

Explanation: "with a dog"

"a dog": `n`

Explanation does not contain a given referent.
Tag "the woman" as `n`.

### 3.2.4 Explanation containing Bridging or Unused Unknown Referent

> Does this explanation contain a bridging referent?

An explanation contains a Bridging referent if:

* It contains a tagged referent marked `b` or `bc`
* It contains an untagged bridging referent with a previously introduced anchor

> A woman was loading groceries into her car `u` `anchor:trunk`.
> The dog who was by [the trunk] `b` started barking.

Explanation: "who was by the trunk"

"the trunk": `b`

Explanation contains a bridging referent.
Tag "the dog" as `u`.

> Across the street, a dog `anchor:leash` was barking wildly.
> The woman holding [the leash] `b` started yelling, too.

Explanation: "holding the leash"

"the leash": `b`

Explanation contains a bridging referent.
Tag "the woman" as `u`.

> Across the street, a dog `anchor:leash` was barking wildly.
> The woman holding \[the dog] \['s leash] started yelling, too.

Explanation: "holding the dog's leash"

"the dog": `g` `anchor:leash`

"'s leash": `bc`

Explanation contains a bridging-contained referent (and a given referent).
Tag "the woman" as `u`.

> A woman `anchor:leg` was unloading groceries. 
> The dog standing at her feet started barking.

Explanation: "standing at her feet"

"her legs": `untagged` `b`

Explanation contains a bridging referent.
Tag "the dog" as `u`. 

<!-- the next example sounds funny, similar to two people - the man-->

<!-- > Two cars `cars` `anchor:car crash` were driving down the street way too quickly.
> The woman who saw [the car crash] stopped putting groceries into her car.

<!--Explanation: "who saw the car crash"

<!--"the car crash": `untagged` `b`

<!--Explanation contains a bridging referent.
Tag "the woman" as `u`. -->

An explanation contains an Unused-Unknown referent if:

* It contains a tagged referent marked `u`
* It contains an untagged unused-unknown referent with a previously introduced anchor

> A man was bouncing a ball.
> The woman who was holding [the dog] that was barking at [the ball]
> looked annoyed.

Explanation: "who was holding the dog that was barking at the ball"

"the ball": `ball` `g` `explanation:dog`

"the dog": `dog` `u`

Explanation contains an unused-unknown referent.
Tag "the woman" as `u`.

### 3.2.5 Explanation Containing Locative Phrase

> Does this explanation contain a locative phrase
> that connects it to an existing referent?

We start looking for a locative phrase if
the explanation does not contain a given/bridging/unused-unknown referent.

A locative phrase must clearly connect the referent in question
to a specific existing referent - tagged or untagged.

> I saw a man and a woman walking down the street.
> The dog `u` [that was nearby] `explanation` started barking.

> Then, I saw a blue car `car1` `n` stopping abruptly.
> The car `car2` `u` [behind] `explanation` couldn't stop in time.

> Then, I saw a white car `car2` `n` crash.
> The car `car1` `u` [in front] `explanation` had stopped abruptly.

Locative phrases conecting the referent in question to a new referent
do *not* qualify as unused-unknown explanations.

> There was a man walking down the street.
> The dog `n` 
[that was standing next to a woman `n`] `non-explanation` started barking.

Sometimes an explanation contains neither
a bridging/given/unused-unknown referent nor a locative phrase.
These referents are still tagged as new.

> A man was walking down the street, and dropped his ball.
> The dog `n` [who got scared] `non-explanation` started barking.

### 3.2.6 Span of Referent Explanations

> What qualifies as an explanation?
> How far does an explanation stretch?

An explanation is the material following a referent,
which explains how the referent is related to the rest of the narrative.

The width of the explanation depends on the type of noun phrase headed by the referent:

* Simple - The noun phrase ends after the referent

If the noun phrase is simple, there is no explanation.

> On the other side of the street,
> there was [a woman].

"a woman" ends with the referent, and has no explanation.

> On the other side of the street,
> there was [a big tall woman].

"a big tall woman" ends with the referent, and has no explanation.

> On the other side of the street,
> [a big tall woman], while loading groceries into her car,
> also held back her dog.

"a big tall woman" ends with the referent, and has no explanation.
"while loading groceries into her car" might seem to explain the referent,
but it is not a part of the noun phrase headed by `woman2`,
because it can be moved around in the sentence.

* Preposition - The noun phrase is extended with a prepositional phrase

If the noun phrase is extended by a prepositional phrase,
the explanation continues until the end of the prepositional phrase.

> Across the street,
> there was [a woman with a big, black, barking dog].

"with" introduces a prepositional phrase,
and the explanation continues until the end of that phrase.

> Across the street,
> there was [a woman with a big blue car with an open trunk
> and a dog who was trying to pull away from her].

"with" introduces a prepositional phrase,
and everything else in the sentence 
is explaining the things that the woman is "with".
So, everything else in the sentence is part of the explanation.

> Across the street,
> [A woman with a big blue car whose trunk was open
> and a dog on a leash who was trying to pull away from her],
> while she was trying to hold onto the dog,
> was also putting groceries into her car.

"with" introduces a prepositional phrase,
and everything through "trying to pull away from her"
is explaining the things that `woman2` is "with".

However, "while she was trying to hold onto the dog" 
is not part of the noun phrase,
and could even be moved around in the sentence.

* Relative - The noun phrase is extended by a relative clause

If the noun phrase is extended by a relative clause,
everything within that relative clause is part of the explanation.

Relative clauses start with words like "who", "that", or "which",
or could have them inserted before the start of the clause.

> Across the street,
> there was [a woman who was pulling on her dog's leash].

Everything after "a woman" 
is part of a relative clause introduced with "who",
and is part of the explanation.

> Across the street,
> there was [a woman pulling on her dog's leash].

Everything after "a woman" is part of a relative clause.
Although it is not introduced with "who", 
"who" could be inserted at the beginning of the clause.

> Across the street,
> [A woman putting groceries in a big blue car whose trunk was open,
> and wrestling with a dog on a leash trying to pull away from her],
> while she was trying to hold onto the dog,
> was also putting groceries into her car.

In this case, the relative clause starts with "putting groceries ...",
and ends with "... away from her".
If we inserted "who was" at the start of the relative clause,
it would still make sense.

"while she ..." is a subordinate clause, and not part of the noun phrase.
While the relative clause cannot be moved around in the sentence,
this subordinate clause can be.

### 3.2.7 Referent Explanation Test

We suggest using the following test: 
If you can move the phrase/clause within the sentence, it refers to the verb and DOES NOT COUNT as an explanation for unused unknown. 
If you cannot move the phrase/clause within the sentence, it refers to the referent and COUNTS as an explanation for unused unknown.
      
> She had a dog [with her]. 

[with her] is the phrase in question

> [With her], she had a dog. 

sounds a bit funny, but it’s still grammatical --> it means you can move it, so the phrase [with her] refers to the verb and does **not** count as an unused unknown explanation

>She had a dog, [who ran after the ball]. 

[who ran after the ball] is the clause in question

> [Who ran after the ball] she had a dog 

this is ungrammatical -->  it means you cannot move it, so the clause [who ran after the ball] refers to the referent “dog” and **counts** as an unused unknown explanation


### 3.2.8 Bridging Relationships

> What is a bridging relationship?
> What are some referents with bridging relationships?

Two referents have a bridging relationship
when introducing one implies the other.

If all the referents on one side of a bridging relationship are introduced,
you would expect the referents on the other side to exist also,
and would not be surprised if they appeared in the narrative.

A non-exhaustive list of bridging relationships:

* man, woman <-> couple
* man, woman, baby <-> family
* baby <-> stroller
* drivers <-> cars
* car3 <-> trunk
* dog <-> leash
* car crash <-> cars
* car crash <-> drivers

> There was a woman next to her car `car3` `n` `anchor:trunk`.
> She was putting groceries into the trunk `trunk` `b`.

> OMG, I saw a huge car crash `untagged` `anchor:cars`.
> The two cars `cars` `b` were going way too fast, IMO.

> A woman was holding back her dog `dog` `u` `anchor:leash`,
> but it kept pulling on the leash `leash` `b` she was using.

We have made the decision that bridging relationships work in both directions, 
for everything except for "car crash" to "cars" and "drivers",
since introducing cars does not imply their crash.
The decision concerning the bi-directionality of the other referent pairs can be reviewed in the future.  

> There was a woman putting groceries into her trunk `trunk` `n` `anchor:car3`.
> She was loading them very quickly into the back of [the car] `car3` `b`.

> A woman was holding a bright pink leash `leash` `n` `anchor:dog` very tightly,
> but the dog `dog` `b` kept pulling anyway.

However, bridging relationships do not *always* mean that
referents should be tagged `b`.
See [the R-Type section on bridging](#bridging) for more information.

Additionally, "car accident" frequently appears in introductions,
and so it often will not be counted for bridging relationships.

### 3.2.9 Bridging vs Bridging Contained

> Should I tag this referent as Bridging or Bridging-Contained?

Similar to [New vs. Unused-Unknown](#new-vs-unused-unknown),
tag as `bc` if either:

* The anchor of the referent appears in the same noun phrase as the referent

> A baby `baby` `n` was being walked down the street.
> The father `man` `bc` of the child `baby` `g` `anchor:man` was following close behind.

> A baby `baby` `n` `anchor:man` was being walked down the street.
> The father `man` `b` was following close behind.

* The referent is possessed by its anchor's possessive pronoun

> A car `car1` `n` was driving down the road.
> Its `car1` `g` `anchor:driver1` driver `driver1` `bc` suddenly stopped.

* The referent is a part of a possessive phrase with the anchor

> Two cars `cars` `n` `anchor:car1` stopped in the street.
> [The first car] `car1` `b` `anchor:driver1` 
> ['s driver] `driver1` `bc` got out angrily.

> The first car `car1` `n` `anchor:driver1` stopped in the street.
> The driver `driver1` `b` got out angrily.

### 3.2.10 Unused-Unknown Across Coordination

> Can a possessive pronoun give unused-unknown status to multiple coordinated referents?

Yes,
if the possessive pronoun applies to a coordinated noun phrase,
all referents in that noun phrase are unused-unknown.

> There was a woman with [her dog] `u` and \[groceries] `u`.

## 3.3 Conjoined Referents

### 3.3.1 Explaining Conjoined Referent Pronouns

> If a conjoined referent is a pronoun 
> ("The two cars stopped. [They] didn't stop fast enough"),
> should we mark whether or not it’s explained?

Yep.
It’s possible, for someone to explain a conjoined referent, even if it’s a pronoun, so we’ll just mark all conjoined referents.

> There was a family walking down the street.
> They `family` `g` `1`, a man, a woman, and a child, were walking quickly.

### 3.3.2 Conjoined Referent Members

> When a conjoined referent appears, are members of it treated as given or bridging?
> Also, when members of a conjoined referent appear, is the conjoined referent treated as given or bridging?

If the conjoined referent is just the collection of individual referents, members are treated as given. 
If all members have been previously listed, the conjoined referent is given, too.

Given relationship conjoined referents:

* cars
* drivers

> Two cars were driving down the street.
> The red one `g` was going slow.

> A red car and a blue car drove down the street.
> The cars `g` were going way too fast.

> The drivers got out of the car.
> The first driver `g` looked very angry.

> One car’s driver got out.
> Then the other car’s driver got out.
> The drivers `g` started arguing.


If the conjoined referent has some inferred bridging relationship between it and its members, members are treated as bridging.
If all members have been previously listed, the conjoined referent is bridging.

Bridging relationship conjoined referents:

* couple
* family

> A couple `couple` `n` was walking down the street.
> The husband `man` `b` was bouncing a ball.

> A family `family` `n` was ready to cross the street.
> The father `man` `b` wearing a white shirt had a ball.

> I saw a guy `man` `n` with a ball and a woman `woman1` `n` with a stroller walking across the parking lot.
> The couple `couple` `b` wanted to turn right.

> A man `man`, a woman `woman1`, and a baby `baby` were standing in the parking lot.
> The family `family` `b` looked strange to me.

However, a conjoined referent is not always introduced with the words "couple" or "family". 
Sometimes they are introduced in a way that enumerates the members, e.g. "two pedestrians", "three people", "these people".
If the conjoined referent is introduced in this way, individual members are treated as given.
If all the members are introduced, and then the conjoined referent is introduced in this way, the conjoined referent is treated as given.

Note how the examples below are exactly the same as the examples above, except for the words that introduce "couple" and "family". These words change the relationship between the conjoined referent and its members from new-bridging to new-given.

> Two pedestrians `couple` `n` were walking down the street.
> One of them `man` `g` was bouncing a ball.

> Three people `family` `n` were ready to cross the street.
> One person `man` `g` wearing a white shirt had a ball.

> I saw a guy `man` `n` with a ball and a woman `woman1` `n` with a stroller walking across the parking lot.
> The two pedestrians `couple` `g` wanted to turn right.

> A man `man` `n`, a woman `woman1` `n`, and a baby `baby` `n` were standing in the parking lot.
> These people `family` `g` looked strange to me.


> Okay, but how do I tag "the man" in the following situaiton? 
> There were two people `couple` `n`  walking down the street.
> The man `man` `???` was bouncing a ball.

It's `n` because
"two people" does not need to include a man, and one would not necessarily
expect it to.
"The man" kind of appears out of nowhere so we tag it as `n`.

Note that this rule only applies to "the man" or "the woman", not "the first person/the first one/ one of them"
because "the man" and "the woman" are unexpected, while "the "the first person/the first one/ one of them" are fine.

> There were two people `couple` `n`  walking down the street.
> The woman `woman1` `n` had a stroller.

> There were two people `couple` `n`  walking down the street.
> The first person `woman1` `g` had a stroller.


## 3.4 Phrases

### 3.4.1 One Behind The Other

> Does the phrase "one behind the other" have any referents?

No.
We are treating "one behind the other" as an idiom, so it has no referents.

### 3.4.2 Everyone

> Which referent does "everyone" refer to?

Here are some previous questions about "everyone", and our decisions:

> The car hit into the back of another car. 
> \[Everyone] seemed fine.

`untagged`

"Everyone" could refer to the drivers,
but is also likely to refer to everyone in the parking lot,
including the drivers.
We have no tag for that, so we leave this untagged.

> The man checked with \[everyone] involved in the accident.

`drivers`

Only the drivers were involved in the accident.

<!-- Get context -->
> \[Everybody] got out and [they] were talking.

`drivers` for both

The drivers were the people in the cars,
and so they were the people who got out.
From the video, we know that the two drivers were talking.

> Two cars crashed into each other, 
> and then [everybody] got out and was yelling.

`drivers`

The drivers were the people in the cars,
and so they were the people who got out.
From the video, we know that the two drivers were talking.

### 3.4.3 Either/Neither/None of the

> What do we do with 
> "Either / Neither / None of the [ conjoined referent ]" ?


Since either, neither, and none don’t really refer to a concrete referent,
we will not tag the phrase,
and we will not tag any referents within the phrase.


> None of the family `untagged` looked very happy.

> Neither of the drivers `untagged` was at fault.

> Either one of them `untagged` could have ended the fight.

### 3.4.4 Both of the

What do we do with "Both of the [ conjoined referent ]" ?

This phrase refers to the conjoined referent. Tag the whole phrase, and tag it with whatever the conjoined referent would be on its own.

> The two cars stopped.
> [Both of the drivers] `drivers` `b` got out.

> Two cars crashed in the middle of the street.
> [Both of the people] `couple` `u` who had been walking down the street looked shocked.

### 3.4.5 One of the

> What do we do with "One of the [conjoined referent]" ?

This phrase refers to a single member of the conjoined referent.
If the context gives evidence that it is one or the other of the members, tag the whole phrase as that member.

If there is no evidence to the identity of the referent, treat it like other ambiguous referents, and do not tag it.

> The white car `g` crashed into the blue car `g`.
> One of the drivers `driver1` `b` got out and called the police.

We know that the referent is driver1, because driver1 is the one who calls the police in this scenario.
We know that the referent is bridging, because driver1 has a bridging relationship with the blue car.

> The two drivers `g` crashed into each other.
> One of them `untagged` looked upset.

Both drivers could be described as looking upset.
Since we don’t know which driver the phrase refers to, we don’t tag anything in the phrase.

### 3.4.5 Each Other

> Should we tag "each other" ?

Nope.


## 3.5 Other

### 3.5.1 Counting CU's

> How do we count the 5 CU's between a referent and its most recent co-referent/anchor

An r-type is `-Displaced` if there are 5 CU's *between* the CU containing the referent and the CU containing its most recent co-referent/anchor.
The CU containing the referent and the CU containing the most recent co-referent/anchor are not counted.

The count of CU's should exclude [empty CU's](empty-cu's).

### 3.5.2 Empty CU's

> Which CU's are empty CU's?

Empty CU's are those without words - pauses, tongue clicks, gulping, etc.

<!-- TODO: Add examples -->
<!-- TODO: What about "hmm" -->

### 3.5.3 Apostrophe S

> What do we do with 's phrases, like "the man's ball"?

Normally when you see an apostrophe s, you can break the phrase up into a given and an unused-unknown.

However, if there is a [bridging relationship](#bridging-relationships) between the two members of the phrase, the second member might be bridging-contained instead.
This requires a bridging relationship, though, and most apostrophe s’s will be unused-unknown.

> A woman was getting her groceries. 
> The woman `g` [‘s dog] `u` ran into the road.

> A car pulled over.
> The car `g` [‘s driver] `bc` got out, and started yelling.

Additionally, if the possessor of the phrase is New,
the possessed referent is also New.

> On the other side of the street, a woman['s dog] `n` was barking.

> On the other side of the street,
> [A woman] `n` ['s dog] `n` ['s leash] `n` was being pulled apart.
        
### 3.5.4 Possessive Pronouns

> What do we do with phrases containing possessive pronouns ("his ball")?

Possessive pronoun phrases are either unused-unknown or bridging (never bridging-contained).
If there is a bridging relationship, then bridging. Otherwise unused-unknown.

> A woman was in the parking lot.
> [Her groceries] `u` fell.

> One of the drivers stopped suddenly.
> [Their car] `b` screeched really loud.

In some rare cases, a referent with a possessive pronoun can be new,
if the speaker failed to introduce the possessor.

> On the other side of the street, [her dog] `n` barked.

Since `woman2` has never been introduced, we tag "her dog" as `n`.

### 3.5.5 Possessive Pronoun "whose"

> How do we tag "whose" in referent noun phrases such as "There was a woman whose car ..."

Tag "whose" as part of the referent that comes after.

> There was a woman [whose car] `u` was very spacious.


### 3.5.6 Wh-Words and Possessive Pronouns

> Should we tag wh-words or possessive pronouns that are not attached to a referent?

Nope!
We tag only noun phrases that are headed by nouns and personal pronouns.

> A man `n` was in the parking lot.
> He `g` was happy.

> A man `n` was in the parking lot.
> In his `untagged` hand was [his ball] `u`.

> There was a woman.
> The man `u` who `untagged` was with her looked confused.

### 3.5.7 Repetitions
> What do we do with repeated references ("A ball - a ball was rolling ...")?

If a referent is repeated without additional information,
tag only the last referent - the one the speaker eventually decided on.

> A man `untagged` was, a man `n` was walking down the street.

However,
if the repetition results in a phrase that can be interpreted as `+fe`,
tag it as such.

> And the car `g` um (-) the blue car `g+fe` um (-) stopped...

### 3.5.8 Identifying Repetitions

<!-- Add to 00-referents -->
> Does this example contain a repetition?

Here are some previous questions about repetitions, and our decisions.
The referents in question are marked with `[]` brackets:

> A woman was closing [her trunk], opening [it], and ...

The speaker changed the verb but not the referent.
Tag both referents normally.

> The car behind him - hit [it] also - hit [the car] - [the other car]

The verb does not change, but the referent does.
Tag "it" `g`, "the car" `g+fe`and "the other car" `g+fe`.

> And the guy with [the ball] who accidentally dropped [the ball] ...

The whole prepositional phrase is replaced by a relative clause.
Tag only the second "the ball".

### 3.5.9 Tagging Unclear Referents

<!-- Add to 00-referents -->
> How confusing can a referent be before we decide not to tag the it?

Here are some examples, and our decisions.
The referents in question are marked with `[]` brackets:

> I saw a lady, and [a boy] next to her bouncing a ball.

`man` - `u`

"a boy" is slightly confusing,
but we can still understand that the speaker meant `man`,
and it would disrupt the narrative not to include it.

> ... so the [owner] of [the cars] called 911.

Neither is tagged.

There is no single owner of two cars.

> The two people came out of their cars and [a man] with the white shirt called the police.

`driver` - `g`

We know that driver1 called the police,
so we can assume that's who they were referring to.

> [They] both came out, and [one of them] called the police

"They": `drivers` - `g`

"One of them": `driver1` - `g`

> I think [someone] like called 911

`driver1`

> The man helped the woman. Uh, [she] helped her pick up her groceries.

`man`

This is likely to be a slip of the tongue,
and in the actual narrative, the man helps the woman.

> ... which distracted a dog that was in the road behind [a car].

Untagged

"a car" is unlikely to be `car3`,
and no other car in the parking lot is tagged.

> [The passengers] got out and called the police.

Untagged

There were no passengers in the cars.

> The car behind him was coming after him,
> so [he] crashed into [that car] too.

Both untagged

"that car" has to refer to "the car behind him", which is `car2`.
Because of this, "he" must refer to `driver1`,
but `driver1` and `car1` were crashed into by `driver2` and `car2`.
So, this sentence doesn't make sense.

### 3.5.10 Generic Referents

> Is this referent generic, and should we tag it?


Here are some examples, and our decisions:

> The woman was holding her dog by [the leash].

`gen`

"the leash" is generic.
We feel that "by the leash" is a set phrase,
that does not refer to the specific leash the dog was held by,
but to the action of holding a dog by any leash.

> Both drivers got out of [the car]

`gen`

"the car" is generic for the same reason,
"get out of the car" just refers to getting out of any car.

> Both drivers got out of [the vehicle]

`gen`

As with "car", so with "vehicle".


## 3.6 Technical

### 3.6.1 Hide Tiers

> EXMARaLDA has too many tiers. Can I hide some?

Yes! To hide tiers in Exmaralda, without deleting them:

* Select a tier on the left, or use shift-click to select multiple tiers
* In the top menu, go to Tier > Hide Tier

### 3.6.2 Merge Cells

> Is there a way to merge cells and immediately begin typing?

Yes.
If you use the merge-cells button, you have to click on the merged cell to type into it.
However, if you instead use the merge-cells shortcut (ctrl-1 on Windows), you can immediately begin typing in the merged cell.

<!--chapter:end:03-questions.Rmd-->

